version: '3'
services:
  nginx:
    container_name: nginx
    #network_mode: "bridge"
    build:
      context: ../Nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
      #- 443:443
    volumes:
      #- /var/vestec/certs:/var/vestec/certs
      - ../Nginx/static/:/var/www/
    links:
      - externalservices:externalservices
    networks:
      - vestec

  externalservices:
    container_name: externalservices
    build:
      context: ../
      dockerfile: ExternalServices/Dockerfile
    ports:
      - 8000:8000
    environment:
      VESTEC_SM_URI: "http://simmanager:5500/SM"
      VESTEC_EDI_URI: "http://edi:5501/EDImanager"
      VESTEC_MSM_URI: "http://msm:5502/MSM"
      VESTEC_DM_URI : "http://datamanager:5503/DM"
      VESTEC_SHARED_FILE_LOCATION : "/shared_data"
      JWT_PASSWD: "SECRET"  # to be replaced by docker secrets
      PYTHONUNBUFFERED: 1
    env_file:
      - environment_variables.env
    volumes:
      - "/shared_data:/shared_data"
    networks:
      - vestec

  simmanager:
    container_name: simmanager
    depends_on:
      - "maria"
    build:
      context: ../
      dockerfile: SimulationManager/Dockerfile
    #WE ONLY NEED THIS IF WE ARE USING SQLITE
    # volumes:
    #   - "../Database:/database"
    environment:
      VESTEC_MSM_URI: "http://msm:5502/MSM"
      VESTEC_SHARED_FILE_LOCATION : "/shared_data"
      PYTHONUNBUFFERED: 1
    env_file:
      - environment_variables.env
    volumes:
      - "/shared_data:/shared_data"
    networks:
      - vestec

  msm:
    container_name: msm
    depends_on:
      - "maria"
    build:
      context: ../
      dockerfile: MachineStatusManager/Dockerfile
    #WE ONLY NEED THIS IF WE ARE USING SQLITE
    # volumes:
    #   - "../Database:/database"
    environment:
      VESTEC_SHARED_FILE_LOCATION : "/shared_data"
      PYTHONUNBUFFERED: 1
    env_file:
      - environment_variables.env
    volumes:
      - "/shared_data:/shared_data"
    networks:
      - vestec

  machineinterface:
    container_name: machineinterface
    depends_on:
      - "rmq"
      - "maria"
    build:
      context: ../
      dockerfile: MachineInterface/Dockerfile
    #WE ONLY NEED THIS IF WE ARE USING SQLITE
    # volumes:
    #   - "../Database:/database"
    environment:
      VESTEC_SHARED_FILE_LOCATION : "/shared_data"    
      PYTHONUNBUFFERED: 1
    env_file:
      - environment_variables.env
    volumes:
      - "/shared_data:/shared_data"
    networks:
      - vestec

  edi:
    container_name: edi
    depends_on:
      - "maria"
    build:
      context: ../
      dockerfile: ExternalDataInterface/Dockerfile
    #WE ONLY NEED THIS IF WE ARE USING SQLITE
    # volumes:
    #   - "../Database:/database"
    environment:
      VESTEC_SHARED_FILE_LOCATION : "/shared_data"    
      PYTHONUNBUFFERED: 1
    env_file:
      - environment_variables.env
    volumes:
      - "/shared_data:/shared_data"
    networks:
      - vestec

  maria:
    container_name: mariadb
    image: mariadb
    environment:
      MYSQL_DATABASE: "vestec"
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - "../Database/mariadb:/var/lib/mysql"
      #- "/var/vestec/db:/var/lib/mysql"
    networks:
      - vestec
    
      
  rmq:
    container_name: rabbitmq
    image: rabbitmq
    networks:
      - vestec
  
  workflow:
    container_name: workflowManager
    depends_on:
      - "rmq"
      - "maria"
    build:
      context: ../
      dockerfile: WorkflowManager/Dockerfile
    environment:
      VESTEC_SM_URI: "http://simmanager:5500/SM"
      VESTEC_EDI_URI: "http://edi:5501/EDImanager"
      VESTEC_MSM_URI: "http://msm:5502/MSM"
      VESTEC_DM_URI : "http://datamanager:5503/DM"
      VESTEC_SHARED_FILE_LOCATION : "/shared_data"
      PYTHONUNBUFFERED: 1
    env_file:
      - environment_variables.env
    volumes:
      - "/shared_data:/shared_data"
    networks:
      - vestec

  datamanager:
    container_name: DataManager
    depends_on:
      - "maria"
    build:
      context: ../
      dockerfile: DataManager/Dockerfile
    environment:
      VESTEC_SHARED_FILE_LOCATION : "/shared_data"
      PYTHONUNBUFFERED: 1
    env_file:
      - environment_variables.env
    volumes:
      - "/shared_data:/shared_data"
    networks:
      - vestec
    

networks:
  vestec:
    driver: "bridge"
